name: 'CI'
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v10
    - uses: actions/checkout@v2
    - uses: akirak/elinter@v4
      with:
        experimental: warn
    - run: elinter -t --ert-runner -e latest
