name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - snapshot

    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v10

    - uses: akirak/elinter@v4.0-pre-1
      env:
        EMACS_VERSION: ${{ matrix.emacs-version }}

    - name: Run tests
      run: 'make test'
      env:
        EMACS_VERSION: ${{ matrix.emacs-version }}
